name: Feature request
description: Suggest an idea for overflight
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What would you like to do?
      description: Describe the problem or the thing that would make overflight more useful.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you have considered
    validations:
      required: false
